Rails-Facebook-Odin-main/config/routes.rb
Rails.application.routes.draw do
  # get 'profiles/show'
  # get 'profiles/edit'
  root to: 'posts#index'

  get 'users/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/auth/:provider/callback', to: 'sessions#create'


  resources :posts, only: [:create, :show, :edit, :update, :index, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]

  resources :profiles, only: [:show, :edit, :update]
  resources :requests, only: [:create, :update, :index]

end

Rails-Facebook-Odin-main/app/models/profile.rb
class Profile < ApplicationRecord

has_one :profile, class_name: "Profile"
  belongs_to :user

  # for paperclip for file attachment functionality:
  has_attached_file :avatar, styles: { medium: "175x175#", thumb: "100x100#", tac: "20x20#" },
                             default_url: 'https://visit.nemedic.com/storage/default.jpg'
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png"]

  validate  :birth_date_cannot_be_in_the_future
  validates :gender, length: { maximum: 100 }
  validates :location, length: { maximum: 255 }
  validates :bio, length: { maximum: 2000 }

  has_attached_file :cover, styles: { large: "851x358#" }
  validates_attachment_content_type :cover, content_type: ["image/jpg", "image/jpeg", "image/png"]

  def birth_date_cannot_be_in_the_future
    errors.add(:birthday, "can't be in the future") if
    !birthday.blank? and birthday > Date.today
  end


end

Rails-Facebook-Odin-main/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = Profile.find(params[:id])
    @posts = @profile.user.posts.page(params[:page]).per(10)
    @comment = Comment.new
  end

  def edit
    @profile = current_user.profile
  end

  def update
    
    if profile.update(profile_params)
      flash[:success] = "Your profile has been updated"
      redirect_to profile
    else
      render 'edit'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:birthday, :gender, :location, :bio, :avatar, :cover)
  end

  def profile
    @profile ||= Profile.find(params[:id])
  end

end

Rails-Facebook-Odin-main/app/views/profiles/edit.html.erb
<!-- <div class="profiles-show"> -->

<div class="cover-background">
  <% if @profile.cover.exists? %>
    <%= image_tag @profile.cover.url(:large), class: "cover-image" %>
  <% end %>
</div>

<div class="user-image">
  <%= image_tag @profile %>
</div>


<div class="cover-content">


  <p class ="cover-name">
    <%= @profile.user.first_name %> <%= @profile.user.last_name %>
  </p>

</div>

<div class="user-info-left-background profile-edit"></div>

<div class="user-info-left profile-edit">

  <%= form_for @profile do |f| %>


      <%= f.label :avatar, fa_icon('image', type: :solid, text: "Change Avatar", color: 'rgb(66, 103, 178)'), class: 'photo-label avatar-label' %>
      <%= f.file_field :avatar, class: 'post-photo profile-photo-select' %>

      <%= f.label :cover, fa_icon('image', type: :solid, text: "Change Cover Photo", color: 'rgb(66, 103, 178)'), class: 'photo-label cover-photo-label' %>
      <%= f.file_field :cover, class: 'post-photo cover-photo-select' %>
      <br/>

      <div class="edit-profile-fields">
        <%= f.label :birthday, "Birthday" %>
        <%= f.date_field :birthday, autocomplete: "off" %>
        <br/>

        <%= f.label :gender, "Gender" %>
        <%= f.text_field :gender, autocomplete: "off" %>
        <br/>

        <%= f.label :location, "City" %>
        <%= f.text_field :location %>
        <br/>

        <%= f.label :bio, "About Me" %>
        <%= f.text_field :bio %>
        <br/>
      </div>

        <%= f.submit "Save Your Profile", class: "profile-edit-submit-button" %>
        <br/>

  <% end %>

</div>


<!-- </div> -->

Rails-Facebook-Odin-main/app/views/profiles/show.html.erb
<!-- <div class="profiles-show"> -->

<div class="cover-background">
  <% if @profile.cover.exists? %>
    <%= image_tag @profile.cover.url(:large), class: "cover-image" %>
  <% end %>
</div>

<div class="user-image">
  <%= image_tag @profile %>
</div>


<div class="cover-content">


  <p class ="cover-name">
    <%= @profile.user.first_name %> <%= @profile.user.last_name %>
  </p>

  <% unless current_user == @profile.user %>
    <% if current_user.requesters.where('requests.accepted = ?', 0).include?(@profile.user) %>
      <%= link_to "Accept Friend Request", request_path(id: current_user.received_requests.find_by(requester_id: @profile.user.id).id, request: { requester_id: @profile.user.id }), method: :put, class: "add-friend-button" %>
    <% elsif current_user.requesters.include?(@profile.user) %>
    <% elsif !current_user.requestees.include?(@profile.user) %>
      <%= link_to fa_icon('user-plus', type: :solid, style: 'color:white', text: "Add Friend"), requests_path(request: { requestee_id: @profile.user.id }), method: :post, class: "add-friend-button" %>
    <% end %>
  <% end %>

  <% if @profile.user == current_user %>
    <%= link_to fa_icon('pencil-alt', type: :solid, style: 'color:white', text: "Edit Your Profile"), edit_profile_path(current_user.profile), class: "edit-your-profile-button"%>
  <% end %>

</div>

<div class="user-info-left-background"></div>

<div class="user-info-left">
  <p>
    <i>Date of Birth:</i>
    <%= @profile.birthday %>
    <br/>

    <i>Gender:</i>
    <%= @profile.gender %>
    <br/>

    <i>City:</i>
    <%= @profile.location %>
    <br/>

    <i>About Me:</i>
    <%= @profile.bio %>
  </p>
</div>

<div class="friends-background"></div>

<div class="friends">
  <% if @profile.user.friends.count > 0 %>
    <h2><%= @profile.user.first_name %>'s friends:</h2>
    <div class="friends-grid">
        <% @profile.user.friends.first(4).each do |friend| %>
          <div>
            <%= link_to(friend.profile) do %>
              <%= image_tag friend.profile, size: '100x100' %>
            <% end %>

            <p class="friend-name">
              <%= friend.first_name %>
            </p>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

<div class="user-posts">
  <% if @posts.count > 0 %>
    <% @posts.each do |post| %>
      <div class="post">
        <p class="post-header">
          <span>
            <%= link_to(post.user.profile) do %>
              <%= image_tag post.user.profile, class:'tac-image' %>
            <% end %>

            <%= link_to "#{post.user.first_name}", post.user.profile, class: "user-name" %>
          </span>
          <%= link_to distance_of_time_in_words(Time.now, post.created_at)+ ' ago', post, class: 'timestamp' %>
          <% if current_user.id == post.user_id %>
          <span class="edit-delete-post">
            <%= link_to 'Edit Post', edit_post_path(post) %>
            <%= link_to 'Delete', post, method: :delete, data: {confirm: "Are you sure?"} %>
          </span>
          <% end %>
        </p>
        <p class="post-content">
          <%= post.content %><br/>
          <% if post.image.exists? %>
            <%= image_tag post %><br/>
          <% end %>
        </p>

        <div class="like-comment-buttons">
          <% like = post.likes.where("user_id = ?", current_user.id) %>
          <% if like.empty? %>
          <%= button_to likes_path(like: {post_id: post.id} ), method: :post, class: "like-button" do %>
            <%= fa_icon('thumbs-up', type: :regular, text: "Like") %>
          <% end %>
          <% else %>
            <%= button_to like.first, method: :delete, class: "like-button unlike" do %>
              <%= fa_icon('thumbs-up', type: :solid, text: "Like") %>
            <% end %>
          <% end %>
          <button class="comment-button"><i class="far fa-comment-alt"></i> Comment</button>
        </div>

        <% if post.likes.count > 0 %>

          <p class="liked-by">
            <%= fa_icon('thumbs-up', type: :solid, style: 'color:rgb(66,103,178)') %>
            <% case post.likes.count %>
            <% when 1 %>
                <% user = User.find(post.likes.first.user_id) %>
                <strong>
                  <%= link_to "#{user.first_name} #{user.last_name}", user.profile, class: "user-name" %>
                </strong>
            <% when 2 %>

              <% post.likes.each_with_index do |like, index| %>
                <% user = User.find(like.user_id) %>
                <strong>
                  <% unless index == post.likes.count - 1 %>
                    <%= link_to "#{user.first_name} #{user.last_name}", user.profile, class: "user-name" %> and
                  <% else %>
                    <%= link_to "#{user.first_name} #{user.last_name}", user.profile, class: "user-name" %>
                  <% end %>
                </strong>

              <% end %>

            <% else %>
              <% user1 = User.find(post.likes.first.user_id) %>
              <% user2 = User.find(post.likes.second.user_id) %>
              <strong>
                <%= link_to "#{user1.first_name} #{user1.last_name}", user1.profile, class: "user-name" %>,
                <%= link_to "#{user2.first_name} #{user2.last_name}", user2.profile, class: "user-name" %>
                  <%= "and " + pluralize(post.likes.count - 2, "other") %>
              </strong>
            <% end %>

          </p>

        <% end %>

        <% if post.comments.count > 0 %>
        <div class="all-comments">
          <% post.comments.each do |comment| %>
            <% user = User.find(comment.user_id) %>
            <%= link_to(user.profile) do %>
              <%= image_tag user.profile, class: 'tac-image comment-image' %>
            <% end %>

            <p class="comment">
              <span class="comment-content">
                <strong><%= link_to "#{user.first_name} #{user.last_name}", user.profile, class: "user-name" %></strong> <%= comment.content %>
              </span>
              <% if current_user.id == comment.user_id %>
                <span class="edit-delete-comment">
                  <%= link_to 'Edit', edit_comment_path(comment) %>
                  <%= link_to 'Delete', comment, method: :delete, data: {confirm: "Are you sure?"} %>
                </span>
              <% end %>
            </p>
          <% end %>
        </div>
        <% end %>

        <%= form_for(@comment) do |f| %>
          <%= link_to(current_user.profile) do %>
            <%= image_tag current_user.profile, class: 'tac-image new-comment-image' %>
          <% end %>

          <%= f.text_area :content, class: "comment-field", placeholder: "Write a comment...", rows: "1"  %>
          <%= f.hidden_field :post_id, value: post.id %>
          <%= f.submit "Comment" %>
        <% end %>
      </div>
    <% end %>
    <%= link_to_previous_page @posts, 'Previous Page', class: "previous-page" %>
    <%= link_to_next_page @posts, 'Next Page', class: "next-page" %>
  <% end %>
</div>
<!-- </div> -->